/*
 * ChannelEngine API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.channelengine.apiclient.api;

import com.channelengine.apiclient.ApiException;
import com.channelengine.apiclient.model.CollectionOfChannelShipmentResponse;
import org.joda.time.DateTime;
import com.channelengine.apiclient.model.MerchantShipmentRequest;
import com.channelengine.apiclient.model.MerchantShipmentTrackingRequest;
import com.channelengine.apiclient.model.ModelApiResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShipmentApi
 */
@Ignore
public class ShipmentApiTest {

    private final ShipmentApi api = new ShipmentApi();

    
    /**
     * Merchant: Create Shipment
     *
     * For merchants.    Mark (part of) an order as shipped.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void shipmentCreateTest() throws ApiException {
        MerchantShipmentRequest model = null;
        ModelApiResponse response = api.shipmentCreate(model);

        // TODO: test validations
    }
    
    /**
     * Channel: Get Shipments
     *
     * For channels.    Gets all shipments created since the supplied date.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void shipmentIndexTest() throws ApiException {
        DateTime createdSince = null;
        CollectionOfChannelShipmentResponse response = api.shipmentIndex(createdSince);

        // TODO: test validations
    }
    
    /**
     * Merchant: Update Shipment
     *
     * For merchants.    Update an existing shipment with tracking information
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void shipmentUpdateTest() throws ApiException {
        String merchantShipmentNo = null;
        MerchantShipmentTrackingRequest model = null;
        ModelApiResponse response = api.shipmentUpdate(merchantShipmentNo, model);

        // TODO: test validations
    }
    
}
