/*
 * ChannelEngine Merchant API
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.channelengine.merchant.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.channelengine.merchant.apiclient.model.ChannelCarrierCollectionMethodApi;
import com.channelengine.merchant.apiclient.model.ChannelCarrierRecommendationApi;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * MerchantShipmentLabelCarrierResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MerchantShipmentLabelCarrierResponse {
  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CODE = "Code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_RESTRICTIONS = "Restrictions";
  @SerializedName(SERIALIZED_NAME_RESTRICTIONS)
  private String restrictions;

  public static final String SERIALIZED_NAME_PRICE = "Price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BigDecimal price;

  public static final String SERIALIZED_NAME_RECOMMENDATION = "Recommendation";
  @SerializedName(SERIALIZED_NAME_RECOMMENDATION)
  private ChannelCarrierRecommendationApi recommendation;

  public static final String SERIALIZED_NAME_COLLECTION_METHOD = "CollectionMethod";
  @SerializedName(SERIALIZED_NAME_COLLECTION_METHOD)
  private ChannelCarrierCollectionMethodApi collectionMethod;

  public static final String SERIALIZED_NAME_HANDOVER_DATE_TIME = "HandoverDateTime";
  @SerializedName(SERIALIZED_NAME_HANDOVER_DATE_TIME)
  private OffsetDateTime handoverDateTime;


  public MerchantShipmentLabelCarrierResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The channel&#39;s name for the shipping label carrier
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The channel's name for the shipping label carrier")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public MerchantShipmentLabelCarrierResponse code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * The channel&#39;s code for the shipping label carrier
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The channel's code for the shipping label carrier")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public MerchantShipmentLabelCarrierResponse restrictions(String restrictions) {
    
    this.restrictions = restrictions;
    return this;
  }

   /**
   * Optional. Any restrictions on this carriers, e.g. weight and/or dimensions
   * @return restrictions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional. Any restrictions on this carriers, e.g. weight and/or dimensions")

  public String getRestrictions() {
    return restrictions;
  }


  public void setRestrictions(String restrictions) {
    this.restrictions = restrictions;
  }


  public MerchantShipmentLabelCarrierResponse price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Optional. Price for this shipping label
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional. Price for this shipping label")

  public BigDecimal getPrice() {
    return price;
  }


  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public MerchantShipmentLabelCarrierResponse recommendation(ChannelCarrierRecommendationApi recommendation) {
    
    this.recommendation = recommendation;
    return this;
  }

   /**
   * Get recommendation
   * @return recommendation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ChannelCarrierRecommendationApi getRecommendation() {
    return recommendation;
  }


  public void setRecommendation(ChannelCarrierRecommendationApi recommendation) {
    this.recommendation = recommendation;
  }


  public MerchantShipmentLabelCarrierResponse collectionMethod(ChannelCarrierCollectionMethodApi collectionMethod) {
    
    this.collectionMethod = collectionMethod;
    return this;
  }

   /**
   * Get collectionMethod
   * @return collectionMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ChannelCarrierCollectionMethodApi getCollectionMethod() {
    return collectionMethod;
  }


  public void setCollectionMethod(ChannelCarrierCollectionMethodApi collectionMethod) {
    this.collectionMethod = collectionMethod;
  }


  public MerchantShipmentLabelCarrierResponse handoverDateTime(OffsetDateTime handoverDateTime) {
    
    this.handoverDateTime = handoverDateTime;
    return this;
  }

   /**
   * Optional. When to handover the package to the carrier  It is in the ISO format including the timezone offset.  E.g. 2020-10-03T18:00:00+02:00  which is 3rd Oct 2020, at 18:00 PM in Amsterdam (Summer Time aka CEST: UTC +2:00 )
   * @return handoverDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional. When to handover the package to the carrier  It is in the ISO format including the timezone offset.  E.g. 2020-10-03T18:00:00+02:00  which is 3rd Oct 2020, at 18:00 PM in Amsterdam (Summer Time aka CEST: UTC +2:00 )")

  public OffsetDateTime getHandoverDateTime() {
    return handoverDateTime;
  }


  public void setHandoverDateTime(OffsetDateTime handoverDateTime) {
    this.handoverDateTime = handoverDateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantShipmentLabelCarrierResponse merchantShipmentLabelCarrierResponse = (MerchantShipmentLabelCarrierResponse) o;
    return Objects.equals(this.name, merchantShipmentLabelCarrierResponse.name) &&
        Objects.equals(this.code, merchantShipmentLabelCarrierResponse.code) &&
        Objects.equals(this.restrictions, merchantShipmentLabelCarrierResponse.restrictions) &&
        Objects.equals(this.price, merchantShipmentLabelCarrierResponse.price) &&
        Objects.equals(this.recommendation, merchantShipmentLabelCarrierResponse.recommendation) &&
        Objects.equals(this.collectionMethod, merchantShipmentLabelCarrierResponse.collectionMethod) &&
        Objects.equals(this.handoverDateTime, merchantShipmentLabelCarrierResponse.handoverDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, code, restrictions, price, recommendation, collectionMethod, handoverDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantShipmentLabelCarrierResponse {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    restrictions: ").append(toIndentedString(restrictions)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    recommendation: ").append(toIndentedString(recommendation)).append("\n");
    sb.append("    collectionMethod: ").append(toIndentedString(collectionMethod)).append("\n");
    sb.append("    handoverDateTime: ").append(toIndentedString(handoverDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

