/*
 * ChannelEngine Merchant API
 * ChannelEngine API for merchants
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.channelengine.merchant.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MerchantOrderCommentUpdateRequest
 */

public class MerchantOrderCommentUpdateRequest {
  @SerializedName("MerchantOrderNo")
  private String merchantOrderNo = null;

  @SerializedName("OrderId")
  private Integer orderId = null;

  @SerializedName("MerchantComment")
  private String merchantComment = null;

  public MerchantOrderCommentUpdateRequest merchantOrderNo(String merchantOrderNo) {
    this.merchantOrderNo = merchantOrderNo;
    return this;
  }

   /**
   * Your own order reference for the order you would like to update the comment for
   * @return merchantOrderNo
  **/
  @ApiModelProperty(value = "Your own order reference for the order you would like to update the comment for")
  public String getMerchantOrderNo() {
    return merchantOrderNo;
  }

  public void setMerchantOrderNo(String merchantOrderNo) {
    this.merchantOrderNo = merchantOrderNo;
  }

  public MerchantOrderCommentUpdateRequest orderId(Integer orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * The ChannelEngine order ID of the order you would like to update the comment for
   * @return orderId
  **/
  @ApiModelProperty(value = "The ChannelEngine order ID of the order you would like to update the comment for")
  public Integer getOrderId() {
    return orderId;
  }

  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  public MerchantOrderCommentUpdateRequest merchantComment(String merchantComment) {
    this.merchantComment = merchantComment;
    return this;
  }

   /**
   * The merchant comment you would like add / update for the order
   * @return merchantComment
  **/
  @ApiModelProperty(required = true, value = "The merchant comment you would like add / update for the order")
  public String getMerchantComment() {
    return merchantComment;
  }

  public void setMerchantComment(String merchantComment) {
    this.merchantComment = merchantComment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantOrderCommentUpdateRequest merchantOrderCommentUpdateRequest = (MerchantOrderCommentUpdateRequest) o;
    return Objects.equals(this.merchantOrderNo, merchantOrderCommentUpdateRequest.merchantOrderNo) &&
        Objects.equals(this.orderId, merchantOrderCommentUpdateRequest.orderId) &&
        Objects.equals(this.merchantComment, merchantOrderCommentUpdateRequest.merchantComment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantOrderNo, orderId, merchantComment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantOrderCommentUpdateRequest {\n");
    
    sb.append("    merchantOrderNo: ").append(toIndentedString(merchantOrderNo)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    merchantComment: ").append(toIndentedString(merchantComment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

