/*
 * ChannelEngine Merchant API
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.9.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.channelengine.merchant.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.channelengine.merchant.apiclient.model.MancoReason;
import com.channelengine.merchant.apiclient.model.MerchantCancellationLineRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MerchantCancellationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MerchantCancellationRequest {
  public static final String SERIALIZED_NAME_MERCHANT_CANCELLATION_NO = "MerchantCancellationNo";
  @SerializedName(SERIALIZED_NAME_MERCHANT_CANCELLATION_NO)
  private String merchantCancellationNo;

  public static final String SERIALIZED_NAME_MERCHANT_ORDER_NO = "MerchantOrderNo";
  @SerializedName(SERIALIZED_NAME_MERCHANT_ORDER_NO)
  private String merchantOrderNo;

  public static final String SERIALIZED_NAME_LINES = "Lines";
  @SerializedName(SERIALIZED_NAME_LINES)
  private List<MerchantCancellationLineRequest> lines = new ArrayList<MerchantCancellationLineRequest>();

  public static final String SERIALIZED_NAME_REASON = "Reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  public static final String SERIALIZED_NAME_REASON_CODE = "ReasonCode";
  @SerializedName(SERIALIZED_NAME_REASON_CODE)
  private MancoReason reasonCode;


  public MerchantCancellationRequest merchantCancellationNo(String merchantCancellationNo) {
    
    this.merchantCancellationNo = merchantCancellationNo;
    return this;
  }

   /**
   * The unique cancellation reference used by the Merchant (sku).
   * @return merchantCancellationNo
  **/
  @ApiModelProperty(required = true, value = "The unique cancellation reference used by the Merchant (sku).")

  public String getMerchantCancellationNo() {
    return merchantCancellationNo;
  }


  public void setMerchantCancellationNo(String merchantCancellationNo) {
    this.merchantCancellationNo = merchantCancellationNo;
  }


  public MerchantCancellationRequest merchantOrderNo(String merchantOrderNo) {
    
    this.merchantOrderNo = merchantOrderNo;
    return this;
  }

   /**
   * The unique order reference used by the Merchant (sku).
   * @return merchantOrderNo
  **/
  @ApiModelProperty(required = true, value = "The unique order reference used by the Merchant (sku).")

  public String getMerchantOrderNo() {
    return merchantOrderNo;
  }


  public void setMerchantOrderNo(String merchantOrderNo) {
    this.merchantOrderNo = merchantOrderNo;
  }


  public MerchantCancellationRequest lines(List<MerchantCancellationLineRequest> lines) {
    
    this.lines = lines;
    return this;
  }

  public MerchantCancellationRequest addLinesItem(MerchantCancellationLineRequest linesItem) {
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Get lines
   * @return lines
  **/
  @ApiModelProperty(required = true, value = "")

  public List<MerchantCancellationLineRequest> getLines() {
    return lines;
  }


  public void setLines(List<MerchantCancellationLineRequest> lines) {
    this.lines = lines;
  }


  public MerchantCancellationRequest reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * Reason for cancellation (text).
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Reason for cancellation (text).")

  public String getReason() {
    return reason;
  }


  public void setReason(String reason) {
    this.reason = reason;
  }


  public MerchantCancellationRequest reasonCode(MancoReason reasonCode) {
    
    this.reasonCode = reasonCode;
    return this;
  }

   /**
   * Get reasonCode
   * @return reasonCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MancoReason getReasonCode() {
    return reasonCode;
  }


  public void setReasonCode(MancoReason reasonCode) {
    this.reasonCode = reasonCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantCancellationRequest merchantCancellationRequest = (MerchantCancellationRequest) o;
    return Objects.equals(this.merchantCancellationNo, merchantCancellationRequest.merchantCancellationNo) &&
        Objects.equals(this.merchantOrderNo, merchantCancellationRequest.merchantOrderNo) &&
        Objects.equals(this.lines, merchantCancellationRequest.lines) &&
        Objects.equals(this.reason, merchantCancellationRequest.reason) &&
        Objects.equals(this.reasonCode, merchantCancellationRequest.reasonCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantCancellationNo, merchantOrderNo, lines, reason, reasonCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantCancellationRequest {\n");
    sb.append("    merchantCancellationNo: ").append(toIndentedString(merchantCancellationNo)).append("\n");
    sb.append("    merchantOrderNo: ").append(toIndentedString(merchantOrderNo)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    reasonCode: ").append(toIndentedString(reasonCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

