/*
 * ChannelEngine Merchant API
 * ChannelEngine API for merchants
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.channelengine.merchant.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.channelengine.merchant.apiclient.model.MerchantProductBundlePartResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * MerchantProductBundleResponse
 */

public class MerchantProductBundleResponse {
  @SerializedName("MerchantProductNo")
  private String merchantProductNo = null;

  @SerializedName("Ean")
  private String ean = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("Price")
  private BigDecimal price = null;

  @SerializedName("Parts")
  private List<MerchantProductBundlePartResponse> parts = null;

  public MerchantProductBundleResponse merchantProductNo(String merchantProductNo) {
    this.merchantProductNo = merchantProductNo;
    return this;
  }

   /**
   * Get merchantProductNo
   * @return merchantProductNo
  **/
  @ApiModelProperty(value = "")
  public String getMerchantProductNo() {
    return merchantProductNo;
  }

  public void setMerchantProductNo(String merchantProductNo) {
    this.merchantProductNo = merchantProductNo;
  }

  public MerchantProductBundleResponse ean(String ean) {
    this.ean = ean;
    return this;
  }

   /**
   * Get ean
   * @return ean
  **/
  @ApiModelProperty(value = "")
  public String getEan() {
    return ean;
  }

  public void setEan(String ean) {
    this.ean = ean;
  }

  public MerchantProductBundleResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MerchantProductBundleResponse price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public MerchantProductBundleResponse parts(List<MerchantProductBundlePartResponse> parts) {
    this.parts = parts;
    return this;
  }

  public MerchantProductBundleResponse addPartsItem(MerchantProductBundlePartResponse partsItem) {
    if (this.parts == null) {
      this.parts = new ArrayList<MerchantProductBundlePartResponse>();
    }
    this.parts.add(partsItem);
    return this;
  }

   /**
   * Get parts
   * @return parts
  **/
  @ApiModelProperty(value = "")
  public List<MerchantProductBundlePartResponse> getParts() {
    return parts;
  }

  public void setParts(List<MerchantProductBundlePartResponse> parts) {
    this.parts = parts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantProductBundleResponse merchantProductBundleResponse = (MerchantProductBundleResponse) o;
    return Objects.equals(this.merchantProductNo, merchantProductBundleResponse.merchantProductNo) &&
        Objects.equals(this.ean, merchantProductBundleResponse.ean) &&
        Objects.equals(this.name, merchantProductBundleResponse.name) &&
        Objects.equals(this.price, merchantProductBundleResponse.price) &&
        Objects.equals(this.parts, merchantProductBundleResponse.parts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantProductNo, ean, name, price, parts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantProductBundleResponse {\n");
    
    sb.append("    merchantProductNo: ").append(toIndentedString(merchantProductNo)).append("\n");
    sb.append("    ean: ").append(toIndentedString(ean)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    parts: ").append(toIndentedString(parts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

