/*
 * ChannelEngine Merchant API
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.channelengine.merchant.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.channelengine.merchant.apiclient.model.MerchantAddressResponse;
import com.channelengine.merchant.apiclient.model.MerchantOrderLineResponse;
import com.channelengine.merchant.apiclient.model.OrderStatusView;
import com.channelengine.merchant.apiclient.model.OrderSupport;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * MerchantOrderResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MerchantOrderResponse {
  public static final String SERIALIZED_NAME_ID = "Id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_CHANNEL_NAME = "ChannelName";
  @SerializedName(SERIALIZED_NAME_CHANNEL_NAME)
  private String channelName;

  public static final String SERIALIZED_NAME_CHANNEL_ID = "ChannelId";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ID)
  private Integer channelId;

  public static final String SERIALIZED_NAME_GLOBAL_CHANNEL_NAME = "GlobalChannelName";
  @SerializedName(SERIALIZED_NAME_GLOBAL_CHANNEL_NAME)
  private String globalChannelName;

  public static final String SERIALIZED_NAME_GLOBAL_CHANNEL_ID = "GlobalChannelId";
  @SerializedName(SERIALIZED_NAME_GLOBAL_CHANNEL_ID)
  private Integer globalChannelId;

  public static final String SERIALIZED_NAME_CHANNEL_ORDER_SUPPORT = "ChannelOrderSupport";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ORDER_SUPPORT)
  private OrderSupport channelOrderSupport;

  public static final String SERIALIZED_NAME_CHANNEL_ORDER_NO = "ChannelOrderNo";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ORDER_NO)
  private String channelOrderNo;

  public static final String SERIALIZED_NAME_STATUS = "Status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private OrderStatusView status;

  public static final String SERIALIZED_NAME_IS_BUSINESS_ORDER = "IsBusinessOrder";
  @SerializedName(SERIALIZED_NAME_IS_BUSINESS_ORDER)
  private Boolean isBusinessOrder;

  public static final String SERIALIZED_NAME_CREATED_AT = "CreatedAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "UpdatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_MERCHANT_COMMENT = "MerchantComment";
  @SerializedName(SERIALIZED_NAME_MERCHANT_COMMENT)
  private String merchantComment;

  public static final String SERIALIZED_NAME_BILLING_ADDRESS = "BillingAddress";
  @SerializedName(SERIALIZED_NAME_BILLING_ADDRESS)
  private MerchantAddressResponse billingAddress;

  public static final String SERIALIZED_NAME_SHIPPING_ADDRESS = "ShippingAddress";
  @SerializedName(SERIALIZED_NAME_SHIPPING_ADDRESS)
  private MerchantAddressResponse shippingAddress;

  public static final String SERIALIZED_NAME_SUB_TOTAL_INCL_VAT = "SubTotalInclVat";
  @SerializedName(SERIALIZED_NAME_SUB_TOTAL_INCL_VAT)
  private BigDecimal subTotalInclVat;

  public static final String SERIALIZED_NAME_SUB_TOTAL_VAT = "SubTotalVat";
  @SerializedName(SERIALIZED_NAME_SUB_TOTAL_VAT)
  private BigDecimal subTotalVat;

  public static final String SERIALIZED_NAME_SHIPPING_COSTS_VAT = "ShippingCostsVat";
  @SerializedName(SERIALIZED_NAME_SHIPPING_COSTS_VAT)
  private BigDecimal shippingCostsVat;

  public static final String SERIALIZED_NAME_TOTAL_INCL_VAT = "TotalInclVat";
  @SerializedName(SERIALIZED_NAME_TOTAL_INCL_VAT)
  private BigDecimal totalInclVat;

  public static final String SERIALIZED_NAME_TOTAL_VAT = "TotalVat";
  @SerializedName(SERIALIZED_NAME_TOTAL_VAT)
  private BigDecimal totalVat;

  public static final String SERIALIZED_NAME_ORIGINAL_SUB_TOTAL_INCL_VAT = "OriginalSubTotalInclVat";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_SUB_TOTAL_INCL_VAT)
  private BigDecimal originalSubTotalInclVat;

  public static final String SERIALIZED_NAME_ORIGINAL_SUB_TOTAL_VAT = "OriginalSubTotalVat";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_SUB_TOTAL_VAT)
  private BigDecimal originalSubTotalVat;

  public static final String SERIALIZED_NAME_ORIGINAL_SHIPPING_COSTS_INCL_VAT = "OriginalShippingCostsInclVat";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_SHIPPING_COSTS_INCL_VAT)
  private BigDecimal originalShippingCostsInclVat;

  public static final String SERIALIZED_NAME_ORIGINAL_SHIPPING_COSTS_VAT = "OriginalShippingCostsVat";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_SHIPPING_COSTS_VAT)
  private BigDecimal originalShippingCostsVat;

  public static final String SERIALIZED_NAME_ORIGINAL_TOTAL_INCL_VAT = "OriginalTotalInclVat";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_TOTAL_INCL_VAT)
  private BigDecimal originalTotalInclVat;

  public static final String SERIALIZED_NAME_ORIGINAL_TOTAL_VAT = "OriginalTotalVat";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_TOTAL_VAT)
  private BigDecimal originalTotalVat;

  public static final String SERIALIZED_NAME_LINES = "Lines";
  @SerializedName(SERIALIZED_NAME_LINES)
  private List<MerchantOrderLineResponse> lines = null;

  public static final String SERIALIZED_NAME_PHONE = "Phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_EMAIL = "Email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_COMPANY_REGISTRATION_NO = "CompanyRegistrationNo";
  @SerializedName(SERIALIZED_NAME_COMPANY_REGISTRATION_NO)
  private String companyRegistrationNo;

  public static final String SERIALIZED_NAME_VAT_NO = "VatNo";
  @SerializedName(SERIALIZED_NAME_VAT_NO)
  private String vatNo;

  public static final String SERIALIZED_NAME_PAYMENT_METHOD = "PaymentMethod";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHOD)
  private String paymentMethod;

  public static final String SERIALIZED_NAME_SHIPPING_COSTS_INCL_VAT = "ShippingCostsInclVat";
  @SerializedName(SERIALIZED_NAME_SHIPPING_COSTS_INCL_VAT)
  private BigDecimal shippingCostsInclVat;

  public static final String SERIALIZED_NAME_CURRENCY_CODE = "CurrencyCode";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CODE)
  private String currencyCode;

  public static final String SERIALIZED_NAME_ORDER_DATE = "OrderDate";
  @SerializedName(SERIALIZED_NAME_ORDER_DATE)
  private OffsetDateTime orderDate;

  public static final String SERIALIZED_NAME_CHANNEL_CUSTOMER_NO = "ChannelCustomerNo";
  @SerializedName(SERIALIZED_NAME_CHANNEL_CUSTOMER_NO)
  private String channelCustomerNo;

  public static final String SERIALIZED_NAME_EXTRA_DATA = "ExtraData";
  @SerializedName(SERIALIZED_NAME_EXTRA_DATA)
  private Map<String, String> extraData = null;


  public MerchantOrderResponse id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The unique identifier used by ChannelEngine. This identifier does  not have to be saved. It should only be used in a call to acknowledge the order.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique identifier used by ChannelEngine. This identifier does  not have to be saved. It should only be used in a call to acknowledge the order.")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public MerchantOrderResponse channelName(String channelName) {
    
    this.channelName = channelName;
    return this;
  }

   /**
   * The name of the channel for this specific environment/account.
   * @return channelName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the channel for this specific environment/account.")

  public String getChannelName() {
    return channelName;
  }


  public void setChannelName(String channelName) {
    this.channelName = channelName;
  }


  public MerchantOrderResponse channelId(Integer channelId) {
    
    this.channelId = channelId;
    return this;
  }

   /**
   * The unique ID of the channel for this specific environment/account.
   * @return channelId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique ID of the channel for this specific environment/account.")

  public Integer getChannelId() {
    return channelId;
  }


  public void setChannelId(Integer channelId) {
    this.channelId = channelId;
  }


  public MerchantOrderResponse globalChannelName(String globalChannelName) {
    
    this.globalChannelName = globalChannelName;
    return this;
  }

   /**
   * The name of the channel across all of ChannelEngine.
   * @return globalChannelName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the channel across all of ChannelEngine.")

  public String getGlobalChannelName() {
    return globalChannelName;
  }


  public void setGlobalChannelName(String globalChannelName) {
    this.globalChannelName = globalChannelName;
  }


  public MerchantOrderResponse globalChannelId(Integer globalChannelId) {
    
    this.globalChannelId = globalChannelId;
    return this;
  }

   /**
   * The unique ID of the channel across all of ChannelEngine.
   * @return globalChannelId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique ID of the channel across all of ChannelEngine.")

  public Integer getGlobalChannelId() {
    return globalChannelId;
  }


  public void setGlobalChannelId(Integer globalChannelId) {
    this.globalChannelId = globalChannelId;
  }


  public MerchantOrderResponse channelOrderSupport(OrderSupport channelOrderSupport) {
    
    this.channelOrderSupport = channelOrderSupport;
    return this;
  }

   /**
   * Get channelOrderSupport
   * @return channelOrderSupport
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OrderSupport getChannelOrderSupport() {
    return channelOrderSupport;
  }


  public void setChannelOrderSupport(OrderSupport channelOrderSupport) {
    this.channelOrderSupport = channelOrderSupport;
  }


  public MerchantOrderResponse channelOrderNo(String channelOrderNo) {
    
    this.channelOrderNo = channelOrderNo;
    return this;
  }

   /**
   * The order reference used by the channel.  This number is not guaranteed to be unique accross all orders,  because different channels can use the same order number format.
   * @return channelOrderNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The order reference used by the channel.  This number is not guaranteed to be unique accross all orders,  because different channels can use the same order number format.")

  public String getChannelOrderNo() {
    return channelOrderNo;
  }


  public void setChannelOrderNo(String channelOrderNo) {
    this.channelOrderNo = channelOrderNo;
  }


  public MerchantOrderResponse status(OrderStatusView status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OrderStatusView getStatus() {
    return status;
  }


  public void setStatus(OrderStatusView status) {
    this.status = status;
  }


  public MerchantOrderResponse isBusinessOrder(Boolean isBusinessOrder) {
    
    this.isBusinessOrder = isBusinessOrder;
    return this;
  }

   /**
   * Indicating whether the order is a business order.
   * @return isBusinessOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicating whether the order is a business order.")

  public Boolean getIsBusinessOrder() {
    return isBusinessOrder;
  }


  public void setIsBusinessOrder(Boolean isBusinessOrder) {
    this.isBusinessOrder = isBusinessOrder;
  }


  public MerchantOrderResponse createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date the order was created in ChannelEngine.
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date the order was created in ChannelEngine.")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public MerchantOrderResponse updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The date the order was last updated in ChannelEngine.
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date the order was last updated in ChannelEngine.")

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public MerchantOrderResponse merchantComment(String merchantComment) {
    
    this.merchantComment = merchantComment;
    return this;
  }

   /**
   * The optional comment a merchant can add to an order.
   * @return merchantComment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The optional comment a merchant can add to an order.")

  public String getMerchantComment() {
    return merchantComment;
  }


  public void setMerchantComment(String merchantComment) {
    this.merchantComment = merchantComment;
  }


  public MerchantOrderResponse billingAddress(MerchantAddressResponse billingAddress) {
    
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * Get billingAddress
   * @return billingAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MerchantAddressResponse getBillingAddress() {
    return billingAddress;
  }


  public void setBillingAddress(MerchantAddressResponse billingAddress) {
    this.billingAddress = billingAddress;
  }


  public MerchantOrderResponse shippingAddress(MerchantAddressResponse shippingAddress) {
    
    this.shippingAddress = shippingAddress;
    return this;
  }

   /**
   * Get shippingAddress
   * @return shippingAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MerchantAddressResponse getShippingAddress() {
    return shippingAddress;
  }


  public void setShippingAddress(MerchantAddressResponse shippingAddress) {
    this.shippingAddress = shippingAddress;
  }


  public MerchantOrderResponse subTotalInclVat(BigDecimal subTotalInclVat) {
    
    this.subTotalInclVat = subTotalInclVat;
    return this;
  }

   /**
   * The total value of the order lines including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering).
   * @return subTotalInclVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total value of the order lines including VAT  (in the shop's base currency calculated using the exchange rate at the time of ordering).")

  public BigDecimal getSubTotalInclVat() {
    return subTotalInclVat;
  }


  public void setSubTotalInclVat(BigDecimal subTotalInclVat) {
    this.subTotalInclVat = subTotalInclVat;
  }


  public MerchantOrderResponse subTotalVat(BigDecimal subTotalVat) {
    
    this.subTotalVat = subTotalVat;
    return this;
  }

   /**
   * The total amount of VAT charged over the order lines  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering).
   * @return subTotalVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total amount of VAT charged over the order lines  (in the shop's base currency calculated using the exchange rate at the time of ordering).")

  public BigDecimal getSubTotalVat() {
    return subTotalVat;
  }


  public void setSubTotalVat(BigDecimal subTotalVat) {
    this.subTotalVat = subTotalVat;
  }


  public MerchantOrderResponse shippingCostsVat(BigDecimal shippingCostsVat) {
    
    this.shippingCostsVat = shippingCostsVat;
    return this;
  }

   /**
   * The total amount of VAT charged over the shipping fee  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering).
   * @return shippingCostsVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total amount of VAT charged over the shipping fee  (in the shop's base currency calculated using the exchange rate at the time of ordering).")

  public BigDecimal getShippingCostsVat() {
    return shippingCostsVat;
  }


  public void setShippingCostsVat(BigDecimal shippingCostsVat) {
    this.shippingCostsVat = shippingCostsVat;
  }


  public MerchantOrderResponse totalInclVat(BigDecimal totalInclVat) {
    
    this.totalInclVat = totalInclVat;
    return this;
  }

   /**
   * The total value of the order including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering).
   * @return totalInclVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total value of the order including VAT  (in the shop's base currency calculated using the exchange rate at the time of ordering).")

  public BigDecimal getTotalInclVat() {
    return totalInclVat;
  }


  public void setTotalInclVat(BigDecimal totalInclVat) {
    this.totalInclVat = totalInclVat;
  }


  public MerchantOrderResponse totalVat(BigDecimal totalVat) {
    
    this.totalVat = totalVat;
    return this;
  }

   /**
   * The total amount of VAT charged over the total value of te order  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering).
   * @return totalVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total amount of VAT charged over the total value of te order  (in the shop's base currency calculated using the exchange rate at the time of ordering).")

  public BigDecimal getTotalVat() {
    return totalVat;
  }


  public void setTotalVat(BigDecimal totalVat) {
    this.totalVat = totalVat;
  }


  public MerchantOrderResponse originalSubTotalInclVat(BigDecimal originalSubTotalInclVat) {
    
    this.originalSubTotalInclVat = originalSubTotalInclVat;
    return this;
  }

   /**
   * The total value of the order lines including VAT  (in the currency in which the order was paid for, see CurrencyCode).
   * @return originalSubTotalInclVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total value of the order lines including VAT  (in the currency in which the order was paid for, see CurrencyCode).")

  public BigDecimal getOriginalSubTotalInclVat() {
    return originalSubTotalInclVat;
  }


  public void setOriginalSubTotalInclVat(BigDecimal originalSubTotalInclVat) {
    this.originalSubTotalInclVat = originalSubTotalInclVat;
  }


  public MerchantOrderResponse originalSubTotalVat(BigDecimal originalSubTotalVat) {
    
    this.originalSubTotalVat = originalSubTotalVat;
    return this;
  }

   /**
   * The total amount of VAT charged over the order lines  (in the currency in which the order was paid for, see CurrencyCode).
   * @return originalSubTotalVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total amount of VAT charged over the order lines  (in the currency in which the order was paid for, see CurrencyCode).")

  public BigDecimal getOriginalSubTotalVat() {
    return originalSubTotalVat;
  }


  public void setOriginalSubTotalVat(BigDecimal originalSubTotalVat) {
    this.originalSubTotalVat = originalSubTotalVat;
  }


  public MerchantOrderResponse originalShippingCostsInclVat(BigDecimal originalShippingCostsInclVat) {
    
    this.originalShippingCostsInclVat = originalShippingCostsInclVat;
    return this;
  }

   /**
   * The shipping fee including VAT  (in the currency in which the order was paid for, see CurrencyCode).
   * @return originalShippingCostsInclVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The shipping fee including VAT  (in the currency in which the order was paid for, see CurrencyCode).")

  public BigDecimal getOriginalShippingCostsInclVat() {
    return originalShippingCostsInclVat;
  }


  public void setOriginalShippingCostsInclVat(BigDecimal originalShippingCostsInclVat) {
    this.originalShippingCostsInclVat = originalShippingCostsInclVat;
  }


  public MerchantOrderResponse originalShippingCostsVat(BigDecimal originalShippingCostsVat) {
    
    this.originalShippingCostsVat = originalShippingCostsVat;
    return this;
  }

   /**
   * The total amount of VAT charged over the shipping fee  (in the currency in which the order was paid for, see CurrencyCode).
   * @return originalShippingCostsVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total amount of VAT charged over the shipping fee  (in the currency in which the order was paid for, see CurrencyCode).")

  public BigDecimal getOriginalShippingCostsVat() {
    return originalShippingCostsVat;
  }


  public void setOriginalShippingCostsVat(BigDecimal originalShippingCostsVat) {
    this.originalShippingCostsVat = originalShippingCostsVat;
  }


  public MerchantOrderResponse originalTotalInclVat(BigDecimal originalTotalInclVat) {
    
    this.originalTotalInclVat = originalTotalInclVat;
    return this;
  }

   /**
   * The total value of the order including VAT  (in the currency in which the order was paid for, see CurrencyCode).
   * @return originalTotalInclVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total value of the order including VAT  (in the currency in which the order was paid for, see CurrencyCode).")

  public BigDecimal getOriginalTotalInclVat() {
    return originalTotalInclVat;
  }


  public void setOriginalTotalInclVat(BigDecimal originalTotalInclVat) {
    this.originalTotalInclVat = originalTotalInclVat;
  }


  public MerchantOrderResponse originalTotalVat(BigDecimal originalTotalVat) {
    
    this.originalTotalVat = originalTotalVat;
    return this;
  }

   /**
   * The total amount of VAT charged over the total value of te order  (in the currency in which the order was paid for, see CurrencyCode).
   * @return originalTotalVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total amount of VAT charged over the total value of te order  (in the currency in which the order was paid for, see CurrencyCode).")

  public BigDecimal getOriginalTotalVat() {
    return originalTotalVat;
  }


  public void setOriginalTotalVat(BigDecimal originalTotalVat) {
    this.originalTotalVat = originalTotalVat;
  }


  public MerchantOrderResponse lines(List<MerchantOrderLineResponse> lines) {
    
    this.lines = lines;
    return this;
  }

  public MerchantOrderResponse addLinesItem(MerchantOrderLineResponse linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<MerchantOrderLineResponse>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Get lines
   * @return lines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<MerchantOrderLineResponse> getLines() {
    return lines;
  }


  public void setLines(List<MerchantOrderLineResponse> lines) {
    this.lines = lines;
  }


  public MerchantOrderResponse phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * The customer&#39;s telephone number.
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The customer's telephone number.")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


  public MerchantOrderResponse email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * The customer&#39;s email.
   * @return email
  **/
  @ApiModelProperty(required = true, value = "The customer's email.")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public MerchantOrderResponse companyRegistrationNo(String companyRegistrationNo) {
    
    this.companyRegistrationNo = companyRegistrationNo;
    return this;
  }

   /**
   * Optional. A company&#39;s chamber of commerce number.
   * @return companyRegistrationNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional. A company's chamber of commerce number.")

  public String getCompanyRegistrationNo() {
    return companyRegistrationNo;
  }


  public void setCompanyRegistrationNo(String companyRegistrationNo) {
    this.companyRegistrationNo = companyRegistrationNo;
  }


  public MerchantOrderResponse vatNo(String vatNo) {
    
    this.vatNo = vatNo;
    return this;
  }

   /**
   * Optional. A company&#39;s VAT number.
   * @return vatNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional. A company's VAT number.")

  public String getVatNo() {
    return vatNo;
  }


  public void setVatNo(String vatNo) {
    this.vatNo = vatNo;
  }


  public MerchantOrderResponse paymentMethod(String paymentMethod) {
    
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * The payment method used on the order.
   * @return paymentMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The payment method used on the order.")

  public String getPaymentMethod() {
    return paymentMethod;
  }


  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public MerchantOrderResponse shippingCostsInclVat(BigDecimal shippingCostsInclVat) {
    
    this.shippingCostsInclVat = shippingCostsInclVat;
    return this;
  }

   /**
   * The shipping fee including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering).
   * @return shippingCostsInclVat
  **/
  @ApiModelProperty(required = true, value = "The shipping fee including VAT  (in the shop's base currency calculated using the exchange rate at the time of ordering).")

  public BigDecimal getShippingCostsInclVat() {
    return shippingCostsInclVat;
  }


  public void setShippingCostsInclVat(BigDecimal shippingCostsInclVat) {
    this.shippingCostsInclVat = shippingCostsInclVat;
  }


  public MerchantOrderResponse currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * The currency code for the amounts of the order.
   * @return currencyCode
  **/
  @ApiModelProperty(required = true, value = "The currency code for the amounts of the order.")

  public String getCurrencyCode() {
    return currencyCode;
  }


  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public MerchantOrderResponse orderDate(OffsetDateTime orderDate) {
    
    this.orderDate = orderDate;
    return this;
  }

   /**
   * The date the order was created at the channel.
   * @return orderDate
  **/
  @ApiModelProperty(required = true, value = "The date the order was created at the channel.")

  public OffsetDateTime getOrderDate() {
    return orderDate;
  }


  public void setOrderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
  }


  public MerchantOrderResponse channelCustomerNo(String channelCustomerNo) {
    
    this.channelCustomerNo = channelCustomerNo;
    return this;
  }

   /**
   * The unique customer reference used by the channel.
   * @return channelCustomerNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique customer reference used by the channel.")

  public String getChannelCustomerNo() {
    return channelCustomerNo;
  }


  public void setChannelCustomerNo(String channelCustomerNo) {
    this.channelCustomerNo = channelCustomerNo;
  }


  public MerchantOrderResponse extraData(Map<String, String> extraData) {
    
    this.extraData = extraData;
    return this;
  }

  public MerchantOrderResponse putExtraDataItem(String key, String extraDataItem) {
    if (this.extraData == null) {
      this.extraData = new HashMap<String, String>();
    }
    this.extraData.put(key, extraDataItem);
    return this;
  }

   /**
   * Extra data on the order.
   * @return extraData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Extra data on the order.")

  public Map<String, String> getExtraData() {
    return extraData;
  }


  public void setExtraData(Map<String, String> extraData) {
    this.extraData = extraData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantOrderResponse merchantOrderResponse = (MerchantOrderResponse) o;
    return Objects.equals(this.id, merchantOrderResponse.id) &&
        Objects.equals(this.channelName, merchantOrderResponse.channelName) &&
        Objects.equals(this.channelId, merchantOrderResponse.channelId) &&
        Objects.equals(this.globalChannelName, merchantOrderResponse.globalChannelName) &&
        Objects.equals(this.globalChannelId, merchantOrderResponse.globalChannelId) &&
        Objects.equals(this.channelOrderSupport, merchantOrderResponse.channelOrderSupport) &&
        Objects.equals(this.channelOrderNo, merchantOrderResponse.channelOrderNo) &&
        Objects.equals(this.status, merchantOrderResponse.status) &&
        Objects.equals(this.isBusinessOrder, merchantOrderResponse.isBusinessOrder) &&
        Objects.equals(this.createdAt, merchantOrderResponse.createdAt) &&
        Objects.equals(this.updatedAt, merchantOrderResponse.updatedAt) &&
        Objects.equals(this.merchantComment, merchantOrderResponse.merchantComment) &&
        Objects.equals(this.billingAddress, merchantOrderResponse.billingAddress) &&
        Objects.equals(this.shippingAddress, merchantOrderResponse.shippingAddress) &&
        Objects.equals(this.subTotalInclVat, merchantOrderResponse.subTotalInclVat) &&
        Objects.equals(this.subTotalVat, merchantOrderResponse.subTotalVat) &&
        Objects.equals(this.shippingCostsVat, merchantOrderResponse.shippingCostsVat) &&
        Objects.equals(this.totalInclVat, merchantOrderResponse.totalInclVat) &&
        Objects.equals(this.totalVat, merchantOrderResponse.totalVat) &&
        Objects.equals(this.originalSubTotalInclVat, merchantOrderResponse.originalSubTotalInclVat) &&
        Objects.equals(this.originalSubTotalVat, merchantOrderResponse.originalSubTotalVat) &&
        Objects.equals(this.originalShippingCostsInclVat, merchantOrderResponse.originalShippingCostsInclVat) &&
        Objects.equals(this.originalShippingCostsVat, merchantOrderResponse.originalShippingCostsVat) &&
        Objects.equals(this.originalTotalInclVat, merchantOrderResponse.originalTotalInclVat) &&
        Objects.equals(this.originalTotalVat, merchantOrderResponse.originalTotalVat) &&
        Objects.equals(this.lines, merchantOrderResponse.lines) &&
        Objects.equals(this.phone, merchantOrderResponse.phone) &&
        Objects.equals(this.email, merchantOrderResponse.email) &&
        Objects.equals(this.companyRegistrationNo, merchantOrderResponse.companyRegistrationNo) &&
        Objects.equals(this.vatNo, merchantOrderResponse.vatNo) &&
        Objects.equals(this.paymentMethod, merchantOrderResponse.paymentMethod) &&
        Objects.equals(this.shippingCostsInclVat, merchantOrderResponse.shippingCostsInclVat) &&
        Objects.equals(this.currencyCode, merchantOrderResponse.currencyCode) &&
        Objects.equals(this.orderDate, merchantOrderResponse.orderDate) &&
        Objects.equals(this.channelCustomerNo, merchantOrderResponse.channelCustomerNo) &&
        Objects.equals(this.extraData, merchantOrderResponse.extraData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, channelName, channelId, globalChannelName, globalChannelId, channelOrderSupport, channelOrderNo, status, isBusinessOrder, createdAt, updatedAt, merchantComment, billingAddress, shippingAddress, subTotalInclVat, subTotalVat, shippingCostsVat, totalInclVat, totalVat, originalSubTotalInclVat, originalSubTotalVat, originalShippingCostsInclVat, originalShippingCostsVat, originalTotalInclVat, originalTotalVat, lines, phone, email, companyRegistrationNo, vatNo, paymentMethod, shippingCostsInclVat, currencyCode, orderDate, channelCustomerNo, extraData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantOrderResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    channelName: ").append(toIndentedString(channelName)).append("\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    globalChannelName: ").append(toIndentedString(globalChannelName)).append("\n");
    sb.append("    globalChannelId: ").append(toIndentedString(globalChannelId)).append("\n");
    sb.append("    channelOrderSupport: ").append(toIndentedString(channelOrderSupport)).append("\n");
    sb.append("    channelOrderNo: ").append(toIndentedString(channelOrderNo)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    isBusinessOrder: ").append(toIndentedString(isBusinessOrder)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    merchantComment: ").append(toIndentedString(merchantComment)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    shippingAddress: ").append(toIndentedString(shippingAddress)).append("\n");
    sb.append("    subTotalInclVat: ").append(toIndentedString(subTotalInclVat)).append("\n");
    sb.append("    subTotalVat: ").append(toIndentedString(subTotalVat)).append("\n");
    sb.append("    shippingCostsVat: ").append(toIndentedString(shippingCostsVat)).append("\n");
    sb.append("    totalInclVat: ").append(toIndentedString(totalInclVat)).append("\n");
    sb.append("    totalVat: ").append(toIndentedString(totalVat)).append("\n");
    sb.append("    originalSubTotalInclVat: ").append(toIndentedString(originalSubTotalInclVat)).append("\n");
    sb.append("    originalSubTotalVat: ").append(toIndentedString(originalSubTotalVat)).append("\n");
    sb.append("    originalShippingCostsInclVat: ").append(toIndentedString(originalShippingCostsInclVat)).append("\n");
    sb.append("    originalShippingCostsVat: ").append(toIndentedString(originalShippingCostsVat)).append("\n");
    sb.append("    originalTotalInclVat: ").append(toIndentedString(originalTotalInclVat)).append("\n");
    sb.append("    originalTotalVat: ").append(toIndentedString(originalTotalVat)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    companyRegistrationNo: ").append(toIndentedString(companyRegistrationNo)).append("\n");
    sb.append("    vatNo: ").append(toIndentedString(vatNo)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    shippingCostsInclVat: ").append(toIndentedString(shippingCostsInclVat)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    channelCustomerNo: ").append(toIndentedString(channelCustomerNo)).append("\n");
    sb.append("    extraData: ").append(toIndentedString(extraData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

