/*
 * ChannelEngine Merchant API
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.channelengine.merchant.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.channelengine.merchant.apiclient.model.MerchantProductRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * PatchMerchantProductDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PatchMerchantProductDto {
  public static final String SERIALIZED_NAME_PROPERTIES_TO_UPDATE = "PropertiesToUpdate";
  @SerializedName(SERIALIZED_NAME_PROPERTIES_TO_UPDATE)
  private List<String> propertiesToUpdate = null;

  public static final String SERIALIZED_NAME_MERCHANT_PRODUCT_REQUEST_MODELS = "MerchantProductRequestModels";
  @SerializedName(SERIALIZED_NAME_MERCHANT_PRODUCT_REQUEST_MODELS)
  private List<MerchantProductRequest> merchantProductRequestModels = null;


  public PatchMerchantProductDto propertiesToUpdate(List<String> propertiesToUpdate) {
    
    this.propertiesToUpdate = propertiesToUpdate;
    return this;
  }

  public PatchMerchantProductDto addPropertiesToUpdateItem(String propertiesToUpdateItem) {
    if (this.propertiesToUpdate == null) {
      this.propertiesToUpdate = new ArrayList<String>();
    }
    this.propertiesToUpdate.add(propertiesToUpdateItem);
    return this;
  }

   /**
   * Fields to update
   * @return propertiesToUpdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Fields to update")

  public List<String> getPropertiesToUpdate() {
    return propertiesToUpdate;
  }


  public void setPropertiesToUpdate(List<String> propertiesToUpdate) {
    this.propertiesToUpdate = propertiesToUpdate;
  }


  public PatchMerchantProductDto merchantProductRequestModels(List<MerchantProductRequest> merchantProductRequestModels) {
    
    this.merchantProductRequestModels = merchantProductRequestModels;
    return this;
  }

  public PatchMerchantProductDto addMerchantProductRequestModelsItem(MerchantProductRequest merchantProductRequestModelsItem) {
    if (this.merchantProductRequestModels == null) {
      this.merchantProductRequestModels = new ArrayList<MerchantProductRequest>();
    }
    this.merchantProductRequestModels.add(merchantProductRequestModelsItem);
    return this;
  }

   /**
   * Products to be updated
   * @return merchantProductRequestModels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Products to be updated")

  public List<MerchantProductRequest> getMerchantProductRequestModels() {
    return merchantProductRequestModels;
  }


  public void setMerchantProductRequestModels(List<MerchantProductRequest> merchantProductRequestModels) {
    this.merchantProductRequestModels = merchantProductRequestModels;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchMerchantProductDto patchMerchantProductDto = (PatchMerchantProductDto) o;
    return Objects.equals(this.propertiesToUpdate, patchMerchantProductDto.propertiesToUpdate) &&
        Objects.equals(this.merchantProductRequestModels, patchMerchantProductDto.merchantProductRequestModels);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertiesToUpdate, merchantProductRequestModels);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchMerchantProductDto {\n");
    sb.append("    propertiesToUpdate: ").append(toIndentedString(propertiesToUpdate)).append("\n");
    sb.append("    merchantProductRequestModels: ").append(toIndentedString(merchantProductRequestModels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

