/*
 * ChannelEngine Merchant API
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.9.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.channelengine.merchant.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * VatSettingsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class VatSettingsResponse {
  public static final String SERIALIZED_NAME_COUNTRY_ISO = "CountryIso";
  @SerializedName(SERIALIZED_NAME_COUNTRY_ISO)
  private String countryIso;

  public static final String SERIALIZED_NAME_NO = "No";
  @SerializedName(SERIALIZED_NAME_NO)
  private String no;

  public static final String SERIALIZED_NAME_STANDARD_RATE = "StandardRate";
  @SerializedName(SERIALIZED_NAME_STANDARD_RATE)
  private BigDecimal standardRate;

  public static final String SERIALIZED_NAME_REDUCED_RATE = "ReducedRate";
  @SerializedName(SERIALIZED_NAME_REDUCED_RATE)
  private BigDecimal reducedRate;

  public static final String SERIALIZED_NAME_SUPER_REDUCED_RATE = "SuperReducedRate";
  @SerializedName(SERIALIZED_NAME_SUPER_REDUCED_RATE)
  private BigDecimal superReducedRate;


  public VatSettingsResponse countryIso(String countryIso) {
    
    this.countryIso = countryIso;
    return this;
  }

   /**
   * Get countryIso
   * @return countryIso
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCountryIso() {
    return countryIso;
  }


  public void setCountryIso(String countryIso) {
    this.countryIso = countryIso;
  }


  public VatSettingsResponse no(String no) {
    
    this.no = no;
    return this;
  }

   /**
   * Get no
   * @return no
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNo() {
    return no;
  }


  public void setNo(String no) {
    this.no = no;
  }


  public VatSettingsResponse standardRate(BigDecimal standardRate) {
    
    this.standardRate = standardRate;
    return this;
  }

   /**
   * Get standardRate
   * @return standardRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getStandardRate() {
    return standardRate;
  }


  public void setStandardRate(BigDecimal standardRate) {
    this.standardRate = standardRate;
  }


  public VatSettingsResponse reducedRate(BigDecimal reducedRate) {
    
    this.reducedRate = reducedRate;
    return this;
  }

   /**
   * Get reducedRate
   * @return reducedRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getReducedRate() {
    return reducedRate;
  }


  public void setReducedRate(BigDecimal reducedRate) {
    this.reducedRate = reducedRate;
  }


  public VatSettingsResponse superReducedRate(BigDecimal superReducedRate) {
    
    this.superReducedRate = superReducedRate;
    return this;
  }

   /**
   * Get superReducedRate
   * @return superReducedRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getSuperReducedRate() {
    return superReducedRate;
  }


  public void setSuperReducedRate(BigDecimal superReducedRate) {
    this.superReducedRate = superReducedRate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VatSettingsResponse vatSettingsResponse = (VatSettingsResponse) o;
    return Objects.equals(this.countryIso, vatSettingsResponse.countryIso) &&
        Objects.equals(this.no, vatSettingsResponse.no) &&
        Objects.equals(this.standardRate, vatSettingsResponse.standardRate) &&
        Objects.equals(this.reducedRate, vatSettingsResponse.reducedRate) &&
        Objects.equals(this.superReducedRate, vatSettingsResponse.superReducedRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryIso, no, standardRate, reducedRate, superReducedRate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VatSettingsResponse {\n");
    sb.append("    countryIso: ").append(toIndentedString(countryIso)).append("\n");
    sb.append("    no: ").append(toIndentedString(no)).append("\n");
    sb.append("    standardRate: ").append(toIndentedString(standardRate)).append("\n");
    sb.append("    reducedRate: ").append(toIndentedString(reducedRate)).append("\n");
    sb.append("    superReducedRate: ").append(toIndentedString(superReducedRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

