/*
 * ChannelEngine Merchant API
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.channelengine.merchant.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets WebhookEventType
 */
@JsonAdapter(WebhookEventType.Adapter.class)
public enum WebhookEventType {
  
  ORDERS_CREATE("ORDERS_CREATE"),
  
  PRODUCTS_CHANGE("PRODUCTS_CHANGE"),
  
  RETURNS_CHANGE("RETURNS_CHANGE"),
  
  SHIPMENTS_CHANGE("SHIPMENTS_CHANGE"),
  
  NOTIFICATIONS_CREATE("NOTIFICATIONS_CREATE"),
  
  BUNDLE_PRODUCTS_CHANGE("BUNDLE_PRODUCTS_CHANGE"),
  
  ORDERS_CHANGE("ORDERS_CHANGE");

  private String value;

  WebhookEventType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WebhookEventType fromValue(String value) {
    for (WebhookEventType b : WebhookEventType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<WebhookEventType> {
    @Override
    public void write(final JsonWriter jsonWriter, final WebhookEventType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WebhookEventType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WebhookEventType.fromValue(value);
    }
  }
}

