/*
 * ChannelEngine API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.channelengine.apiclient.model;

import java.util.Objects;
import com.channelengine.apiclient.model.ExtraDataItem;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * MerchantProductResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-08T15:11:49.636+02:00")
public class MerchantProductResponse {
  @SerializedName("IsActive")
  private Boolean isActive = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("Brand")
  private String brand = null;

  @SerializedName("Size")
  private String size = null;

  @SerializedName("Color")
  private String color = null;

  @SerializedName("Ean")
  private String ean = null;

  @SerializedName("ManufacturerProductNumber")
  private String manufacturerProductNumber = null;

  @SerializedName("Stock")
  private Integer stock = null;

  @SerializedName("Price")
  private Double price = null;

  @SerializedName("MSRP")
  private Double MSRP = null;

  @SerializedName("PurchasePrice")
  private Double purchasePrice = null;

  /**
   * The type of VAT which applies to this product.  See: http://ec.europa.eu/taxation_customs/taxation/vat/topics/rates_en.htm
   */
  public enum VatRateTypeEnum {
    @SerializedName("STANDARD")
    STANDARD("STANDARD"),
    
    @SerializedName("REDUCED")
    REDUCED("REDUCED"),
    
    @SerializedName("SUPER_REDUCED")
    SUPER_REDUCED("SUPER_REDUCED");

    private String value;

    VatRateTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("VatRateType")
  private VatRateTypeEnum vatRateType = null;

  @SerializedName("ShippingCost")
  private Double shippingCost = null;

  @SerializedName("ShippingTime")
  private String shippingTime = null;

  @SerializedName("Url")
  private String url = null;

  @SerializedName("ImageUrl")
  private String imageUrl = null;

  @SerializedName("CategoryTrail")
  private String categoryTrail = null;

  @SerializedName("ExtraData")
  private List<ExtraDataItem> extraData = new ArrayList<ExtraDataItem>();

  public MerchantProductResponse isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public MerchantProductResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MerchantProductResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public MerchantProductResponse brand(String brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Get brand
   * @return brand
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBrand() {
    return brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }

  public MerchantProductResponse size(String size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSize() {
    return size;
  }

  public void setSize(String size) {
    this.size = size;
  }

  public MerchantProductResponse color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public MerchantProductResponse ean(String ean) {
    this.ean = ean;
    return this;
  }

   /**
   * Get ean
   * @return ean
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEan() {
    return ean;
  }

  public void setEan(String ean) {
    this.ean = ean;
  }

  public MerchantProductResponse manufacturerProductNumber(String manufacturerProductNumber) {
    this.manufacturerProductNumber = manufacturerProductNumber;
    return this;
  }

   /**
   * Get manufacturerProductNumber
   * @return manufacturerProductNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getManufacturerProductNumber() {
    return manufacturerProductNumber;
  }

  public void setManufacturerProductNumber(String manufacturerProductNumber) {
    this.manufacturerProductNumber = manufacturerProductNumber;
  }

  public MerchantProductResponse stock(Integer stock) {
    this.stock = stock;
    return this;
  }

   /**
   * Get stock
   * @return stock
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStock() {
    return stock;
  }

  public void setStock(Integer stock) {
    this.stock = stock;
  }

  public MerchantProductResponse price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Price, including VAT.
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "Price, including VAT.")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public MerchantProductResponse MSRP(Double MSRP) {
    this.MSRP = MSRP;
    return this;
  }

   /**
   * Manufacturer's suggested retail price
   * @return MSRP
  **/
  @ApiModelProperty(example = "null", value = "Manufacturer's suggested retail price")
  public Double getMSRP() {
    return MSRP;
  }

  public void setMSRP(Double MSRP) {
    this.MSRP = MSRP;
  }

  public MerchantProductResponse purchasePrice(Double purchasePrice) {
    this.purchasePrice = purchasePrice;
    return this;
  }

   /**
   * Get purchasePrice
   * @return purchasePrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPurchasePrice() {
    return purchasePrice;
  }

  public void setPurchasePrice(Double purchasePrice) {
    this.purchasePrice = purchasePrice;
  }

  public MerchantProductResponse vatRateType(VatRateTypeEnum vatRateType) {
    this.vatRateType = vatRateType;
    return this;
  }

   /**
   * The type of VAT which applies to this product.  See: http://ec.europa.eu/taxation_customs/taxation/vat/topics/rates_en.htm
   * @return vatRateType
  **/
  @ApiModelProperty(example = "null", value = "The type of VAT which applies to this product.  See: http://ec.europa.eu/taxation_customs/taxation/vat/topics/rates_en.htm")
  public VatRateTypeEnum getVatRateType() {
    return vatRateType;
  }

  public void setVatRateType(VatRateTypeEnum vatRateType) {
    this.vatRateType = vatRateType;
  }

  public MerchantProductResponse shippingCost(Double shippingCost) {
    this.shippingCost = shippingCost;
    return this;
  }

   /**
   * Get shippingCost
   * @return shippingCost
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getShippingCost() {
    return shippingCost;
  }

  public void setShippingCost(Double shippingCost) {
    this.shippingCost = shippingCost;
  }

  public MerchantProductResponse shippingTime(String shippingTime) {
    this.shippingTime = shippingTime;
    return this;
  }

   /**
   * A textual representation of the shippingtime.  For example, in Dutch: 'Op werkdagen voor 22:00 uur besteld, morgen in huis'
   * @return shippingTime
  **/
  @ApiModelProperty(example = "null", value = "A textual representation of the shippingtime.  For example, in Dutch: 'Op werkdagen voor 22:00 uur besteld, morgen in huis'")
  public String getShippingTime() {
    return shippingTime;
  }

  public void setShippingTime(String shippingTime) {
    this.shippingTime = shippingTime;
  }

  public MerchantProductResponse url(String url) {
    this.url = url;
    return this;
  }

   /**
   * A URL pointing to the merchant's webpage  which displays this product.
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "A URL pointing to the merchant's webpage  which displays this product.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public MerchantProductResponse imageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * A URL at which an image of this product  can be found.
   * @return imageUrl
  **/
  @ApiModelProperty(example = "null", value = "A URL at which an image of this product  can be found.")
  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public MerchantProductResponse categoryTrail(String categoryTrail) {
    this.categoryTrail = categoryTrail;
    return this;
  }

   /**
   * The category to which this product belongs.  Please supply this field in the following format:  'maincategory &gt; category &gt; subcategory'  For example:  'vehicles &gt; bikes &gt; mountainbike'
   * @return categoryTrail
  **/
  @ApiModelProperty(example = "null", value = "The category to which this product belongs.  Please supply this field in the following format:  'maincategory &gt; category &gt; subcategory'  For example:  'vehicles &gt; bikes &gt; mountainbike'")
  public String getCategoryTrail() {
    return categoryTrail;
  }

  public void setCategoryTrail(String categoryTrail) {
    this.categoryTrail = categoryTrail;
  }

  public MerchantProductResponse extraData(List<ExtraDataItem> extraData) {
    this.extraData = extraData;
    return this;
  }

  public MerchantProductResponse addExtraDataItem(ExtraDataItem extraDataItem) {
    this.extraData.add(extraDataItem);
    return this;
  }

   /**
   * An optional list of key-value pairs containing  extra data about this product. This data can be  sent to channels or used for filtering products.
   * @return extraData
  **/
  @ApiModelProperty(example = "null", value = "An optional list of key-value pairs containing  extra data about this product. This data can be  sent to channels or used for filtering products.")
  public List<ExtraDataItem> getExtraData() {
    return extraData;
  }

  public void setExtraData(List<ExtraDataItem> extraData) {
    this.extraData = extraData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantProductResponse merchantProductResponse = (MerchantProductResponse) o;
    return Objects.equals(this.isActive, merchantProductResponse.isActive) &&
        Objects.equals(this.name, merchantProductResponse.name) &&
        Objects.equals(this.description, merchantProductResponse.description) &&
        Objects.equals(this.brand, merchantProductResponse.brand) &&
        Objects.equals(this.size, merchantProductResponse.size) &&
        Objects.equals(this.color, merchantProductResponse.color) &&
        Objects.equals(this.ean, merchantProductResponse.ean) &&
        Objects.equals(this.manufacturerProductNumber, merchantProductResponse.manufacturerProductNumber) &&
        Objects.equals(this.stock, merchantProductResponse.stock) &&
        Objects.equals(this.price, merchantProductResponse.price) &&
        Objects.equals(this.MSRP, merchantProductResponse.MSRP) &&
        Objects.equals(this.purchasePrice, merchantProductResponse.purchasePrice) &&
        Objects.equals(this.vatRateType, merchantProductResponse.vatRateType) &&
        Objects.equals(this.shippingCost, merchantProductResponse.shippingCost) &&
        Objects.equals(this.shippingTime, merchantProductResponse.shippingTime) &&
        Objects.equals(this.url, merchantProductResponse.url) &&
        Objects.equals(this.imageUrl, merchantProductResponse.imageUrl) &&
        Objects.equals(this.categoryTrail, merchantProductResponse.categoryTrail) &&
        Objects.equals(this.extraData, merchantProductResponse.extraData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isActive, name, description, brand, size, color, ean, manufacturerProductNumber, stock, price, MSRP, purchasePrice, vatRateType, shippingCost, shippingTime, url, imageUrl, categoryTrail, extraData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantProductResponse {\n");
    
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    ean: ").append(toIndentedString(ean)).append("\n");
    sb.append("    manufacturerProductNumber: ").append(toIndentedString(manufacturerProductNumber)).append("\n");
    sb.append("    stock: ").append(toIndentedString(stock)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    MSRP: ").append(toIndentedString(MSRP)).append("\n");
    sb.append("    purchasePrice: ").append(toIndentedString(purchasePrice)).append("\n");
    sb.append("    vatRateType: ").append(toIndentedString(vatRateType)).append("\n");
    sb.append("    shippingCost: ").append(toIndentedString(shippingCost)).append("\n");
    sb.append("    shippingTime: ").append(toIndentedString(shippingTime)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    categoryTrail: ").append(toIndentedString(categoryTrail)).append("\n");
    sb.append("    extraData: ").append(toIndentedString(extraData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

